### ISSUE TITLE
Add travis-ci integration

### ISSUE THREAD

**Issue by meaku** [epha/dynamise#10]
As we rely on model from now on, it would be great to add CI to this repo. Travis CI is easy to setup and free of charge for open source projects.

**Comment by flootr** [comment]
:+1:

**Comment by flootr** [comment]
Added a `.travis.yml` to the project 852d90c055e9fc901b2780f8eca22ae94e7e0258

**Comment by meaku** [comment]
I added the aws keys [encrypted to the .travis.yml](http://docs.travis-ci.com/user/environment-variables/).

**Comment by meaku** [comment]
Done using the encrypted aws keys and a local dynalite instance.
