### ISSUE TITLE
Inconsistency between find() and findAll() 

### ISSUE THREAD

**Issue by meaku** [epha/dynamise#16]
We were just discussing the signature of `find()` and `findAll()` and it doesn't seem consistent at the moment. 

As an example i was just calling find against an index passing the indexName via `params` object, which works well: 

```javascript
return client.table("SubjectResource")
        .find({
          IndexName: "ResourcesByType"
        })
        .where("subjectId").equals("subjectId")
        .where("type").equals("invoice")
```

I can't call `findAll()` with two where conditions as we restricted `findAll()` on queries using only the hash key. Although it could be done passing the conditions via `params` it would be more convenient to use the sugar functions. The only downside is that we would need something like `exec` to signal that the query-building is done. 

Furthermore, specifying an index is quite common, and some sugar wrapper would be great for this case. 

A unified version could look the following: 

```javascript

//find by hash
client.table("SubjectResource")
    .find()
    .where("subjectId").equals("subjectId")
    .exec(); 

//find by hash & range 
client.table("SubjectResource")
    .find()
    .where("subjectId").equals("subjectId")
    .where("type").equals("invoice")
    .exec(); 

//find by hash & range using an index
client.table("SubjectResource")
    .find()
    .usingIndex("ResourcesByType")
    .where("subjectId").equals("subjectId")
    .where("type").equals("invoice")
    .exec(); 
```
An automated pagination handling is what i expected of `findAll()` in contrast to `find()`. 
We could ether change the semantics of those functions to the described behavior or solve it using another sugar keyword `all`.  

```javascript
client.table("SubjectResource")
    .find()
    .all() //or findAll
    .where("subjectId").equals("subjectId")
    .where("type").equals("invoice")
    .exec(); 
```

What do you think @flootr @Jonas74 ?

**Comment by meaku** [comment]
There is another inconsistency: `scanAll()` means it handles __pagination__ automatically whereas `findAll()` does not...

**Comment by flootr** [comment]
See f2a23c31a9bf309a2efab4f965f781ed85908d06

**Comment by meaku** [comment]
:+1: 

Should we update `scan` and `scanAll` as well?

**Comment by flootr** [comment]
Imo we actually should do this to be consistent.
