### ISSUE TITLE
jshint quotation marks

### ISSUE THREAD

**Issue by flootr** [epha/dynamise#18]
@meaku 

about quotation marks in .jshintrc

> Warning This option has been deprecated and will be removed in the next major release of JSHint. JSHint is limiting its scope to issues of code correctness. If you would like to enforce rules relating to code style, check out the JSCS project.

http://jshint.com/docs/options/#quotmark

to be closed

**Comment by meaku** [comment]
Should we add JSCS?

**Comment by flootr** [comment]
Actually, I would like to.
We could take the advantages and get code which is **easier to maintain** and more **readable**. Furthermore, it is quite easy to implement / add.

**Comment by flootr** [comment]
90fada87fb9b55ee9117d8d95b27976c10502d7f
