### ISSUE TITLE
Use official amazon document module for transforms

### ISSUE THREAD

**Issue by meaku** [epha/dynamise#3]
I just found https://github.com/awslabs/dynamodb-document-js-sdk which offers transformation and other helpers for the dynamodb client. Might be worth a try as it's an official amazon addition.

**Comment by flootr** [comment]
I would like to do this after finishing the API signature, alongside refactoring the inner layer (prototypes and so on). Thus I consider this to be a long-term issue.

**Comment by flootr** [comment]
fa20d71266f17e6073abaa7dfe0ef01eb4d78962
