### ISSUE TITLE
Add examples for patch

### ISSUE THREAD

**Issue by meaku** [epha/dynamise#42]
@flootr can you add an example on a patch with 
- an attribute deleted
- an attribute modified
- an attribute added

Would be sweet :sunny:

**Comment by flootr** [comment]
Quick and dirty:

```javascript
var item = {
  id: 1,
  name: "Markus",
  email: "top@level.domain"
  age: 99
}

client.table(tableName)
  .patch({
    id: item.id, // cannot be updated (hash)
    email: "super@hero.com", // will be updated
    age: null // will be deleted
  })
  .then(function (res) {
    // res holds the updated item
  });
```

**Comment by flootr** [comment]
I have to correct myself.
> PUT:
Adds the specified attribute to the item. If the attribute already exists, it is replaced by the new value.

Thus you use `PUT` if you want to add another attribute to your item. You will not have to do anything else than adding the attribute to your javascript object. Dynamise will handle the rest for you.

With `ADD` you are able to do a operations like
```
1 ADD: 1 results in 2
[1, 2] ADD: [3] results in [1, 2, 3]
```

**Comment by flootr** [comment]
Example @ [patch()](https://github.com/epha/dynamise#clienttabletablenamepatchitem-)
